version: 1.7.6.{build}
image: Visual Studio 2017


environment:
  matrix:
    - PlatformToolset: VS15
    - PlatformToolset: VS17

platform:
    - x64
    - x86

configuration:
    - Release
    #- Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="x86" set archi=x86
    - if "%platform%"=="x86" set platform_input=x86

    - if "%PlatformToolset%"=="VS15" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%
    - if "%PlatformToolset%"=="VS17" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%
    - nuget restore "%APPVEYOR_BUILD_FOLDER%"\src\CSScriptNpp.Test\packages.config -PackagesDirectory "%APPVEYOR_BUILD_FOLDER%"\src\packages
    - nuget restore "%APPVEYOR_BUILD_FOLDER%"\src\Roslyn.Intellisesne\Roslyn.Intellisense\packages.config -PackagesDirectory "%APPVEYOR_BUILD_FOLDER%"\src\packages


init:
    - git config --global core.autocrlf true

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\src
    - msbuild CSScriptNpp.sln /p:configuration="%configuration%" /p:platform="%platform_input%"  /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    # - cd "%APPVEYOR_BUILD_FOLDER%"\src\CSScriptNpp
    # - ps: >-

    #     if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Release") {
    #         #Push-AppveyorArtifact "bin\$env:PLATFORM\$env:CONFIGURATION\" -FileName CSScriptNpp.dll
    #     }

    #     if ($env:PLATFORM -eq "Any CPU" -and $env:CONFIGURATION -eq "Release") {
    #         Push-AppveyorArtifact "bin\$env:PLATFORM\$env:CONFIGURATION\CSScriptNpp.dll" -FileName CSScriptNpp.dll
    #     }

    #     if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "VS17") {
    #         if($env:PLATFORM -eq "x64"){
    #         $ZipFileName = "CSScriptNpp_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
    #         7z a $ZipFileName bin\$env:PLATFORM\$env:CONFIGURATION\CSScriptNpp.dll
    #         }
    #         if($env:PLATFORM -eq "Any CPU"){
    #         $ZipFileName = "CSScriptNpp_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
    #         7z a $ZipFileName bin\$env:PLATFORM\$env:CONFIGURATION\CSScriptNpp.dll
    #         }
    #     }

artifacts:
  # - path: CSScriptNpp_*.zip
  #   name: releases

deploy:
    # provider: GitHub
    # auth_token:
    #     secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    # artifact: releases
    # draft: false
    # prerelease: false
    # force_update: true
    # on:
    #     appveyor_repo_tag: true
    #     PlatformToolset: VS17
    #     configuration: Release
